# fly.toml app configuration file generated for innerloop-slack-bot on 2026-02-10T16:27:48+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'innerloop-slack-bot'
primary_region = 'bom'

[build]
  dockerfile = "Dockerfile.worker"

[[cron]]
  schedule = "5 0 * * *"
  command = "node runtime/aggregate.js && node runtime/aggregateUsers.js && node runtime/anomaly.js"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
